// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIRQFQ04MhKJVo-kBcdIDq7Zk5Ws0h3Zk',
    appId: '1:989145326487:web:d3978c9923991a6493dad2',
    messagingSenderId: '989145326487',
    projectId: 'user-reg-new-proj',
    authDomain: 'user-reg-new-proj.firebaseapp.com',
    storageBucket: 'user-reg-new-proj.firebasestorage.app',
    measurementId: 'G-X23GR6PT62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbNDPjr2AbnN4UgbWPXtfJCDe_7vru18',
    appId: '1:989145326487:android:c695ba7c8da23d6593dad2',
    messagingSenderId: '989145326487',
    projectId: 'user-reg-new-proj',
    storageBucket: 'user-reg-new-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPtbI8f2Gwtm0mjzcZ8PLeS_w-AXybYg',
    appId: '1:989145326487:ios:f7f6b74f8ffe385b93dad2',
    messagingSenderId: '989145326487',
    projectId: 'user-reg-new-proj',
    storageBucket: 'user-reg-new-proj.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPtbI8f2Gwtm0mjzcZ8PLeS_w-AXybYg',
    appId: '1:989145326487:ios:f7f6b74f8ffe385b93dad2',
    messagingSenderId: '989145326487',
    projectId: 'user-reg-new-proj',
    storageBucket: 'user-reg-new-proj.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIRQFQ04MhKJVo-kBcdIDq7Zk5Ws0h3Zk',
    appId: '1:989145326487:web:ddd263e55ed6c99b93dad2',
    messagingSenderId: '989145326487',
    projectId: 'user-reg-new-proj',
    authDomain: 'user-reg-new-proj.firebaseapp.com',
    storageBucket: 'user-reg-new-proj.firebasestorage.app',
    measurementId: 'G-K29MP882NH',
  );
}